### ISSUE TITLE
关于联合网络的计算问题（question for combine network）

### ISSUE THREAD

**Issue by kingdongkong** [rorytboyle/flexible_cpm#2]
今天比较了原始作者关于CPM算法的应用，发现了一点差别
在我的理解里面，none 与原始作者的代码应该是同样的结果
但是我发现在计算联合网络的时候，flex_cpm使用的是正网络强度和减去负网络的强度和
而原始作者的是将这两个变量都作为一个维度，建立的是多元线性回归
所以想知道这里是有什么深意嘛？谢谢

Today, I compared the original author's code of CPM algorithm and found some difference .
In my understanding, ‘’None‘’ should be the same result as the original author's code .
But I found that flex_CPM uses the sum of positive network strength minus the sum of negative network strength when calculating combine networks .
However, the original author took these two variables as different dimension and established by multiple linear regression . 
So you want to know what's going on here?  thank you！

**Comment by rorytboyle** [comment]
Hi,

Thank you very much for getting in touch.

I based flexible_CPM on the code here (**https://www.nitrc.org/frs/download.php/8071/nn_code.zip**) and the relevant function in that code (**codeshare_behavioralprediction.m**) doesn't explicitly define or calculate combined network strength. 

I calculated combined network strength following the method outlined by Greene et al. 2018 Nature Communications (**https://doi.org/10.1038/s41467-018-04920-3**). This method is outlined on Pg. 2 of the paper:

"Each iteration of the CPM pipeline yields two networks: one comprised of edges that are positively correlated with gF (“correlated network” (CN)) and one comprised of edges that are negatively correlated with gF (“anti-correlated network” (AN)). For simplicity and improved interpretability, **_information in these networks was consolidated by taking the difference between network strength (i.e., summed edge strengths) in the CN and AN_**, and this combined network strength was used to train and test the models".

As such, I calculated combined network strength in CPM_network_strength.m as the sum of all positive thresholded edges minus the sum of all negative thresholded edges. 

I believe this is the correct method based on the Greene et al. 2018 paper but I would be very grateful if you could share the code for the CPM algorithm with the method that you have described?

**Comment by kingdongkong** [comment]
Hi,

Thank you for reply me and provide the source and article.

Actually, I agree with you. But someone provide me another codes.  

`x_pos = [ones(size(train_behav)) train_sumpos];
x_neg = [ones(size(train_behav)) train_sumneg];
x_combined = [ones(size(train_behav)) train_sumpos-train_sumneg];   % from CPM_fit_model.m
x_glm = [ones(size(train_behav)) train_sumpos train_sumneg];   % which I think the GLM (maybe just because i prefer to call the method as "combined"
`
I just show the detail here. Sorry , my English is not very good , same with my code. I understand combined network by [Rosenberg, M., Finn, E., Scheinost, D. et al. A neuromarker of sustained attention from whole-brain functional connectivity. Nat Neurosci 19, 165–171 (2016). ](https://doi.org/10.1038/nn.4179). But during 2016 year , the name is not called CPM. Your code is correct method based on the Greene et al. 2018 paper.

Thank you.

**Comment by rorytboyle** [comment]
Thank you for sharing the code and the Rosenberg et al. article. The GLM method is used in that article and not just positive minus network strength, but given that the Greene et al. article is more recent and that both papers are from the same group, I will stick with the method I have used to calculate combined network strength here. 

I will update the documentation for CPM_network_strength.m to highlight that I am using the method outlined in Greene et al. 2018.

Thank you very much for pointing this difference out!
