### ISSUE TITLE
issue about adjustment of covariates using the flexible CPM

### ISSUE THREAD

**Issue by lirui1125** [rorytboyle/flexible_cpm#3]
Dear Dr. Boyle,

I am now using your newly developed and wonderful toolbox, the Flexible CPM, to conduct my research. During running the program, I encountered a small issue, and so post this here to hope to receive your helpful guidance.

The issue is about the adjustment of covariates (4 covariates were used in my analysis). When I use the option adjust_stage = 'relate' or adjust_stage = 'fit', the program is executed perfectly, but when controlling for the covariates at both feature selection and model fitting steps using the option adjust_stage = 'both', the program encountered an error reporting:

_  Error using Neuromethods_main_analysis_CPM (line 135)

 Unable to perform assignment because the size of the left side is 1-by-4 and the size of the right side is 0-by-0._

 Would you please help me check where the issue lies and if I need to made any changes with the scripts to let it runs correctly.

Thank you and the great toolbox very much!

Rui

**Comment by rorytboyle** [comment]
Hi Rui,

Thank you very much for highlighting this issue. We have updated the extract_parameters_CPM.m function and tested it, and we are able to run adjust_stage = 'both' now without any issues.

Best regards,

Rory.

**Comment by lirui1125** [comment]
Dear Rory,
Thank you very much! The program now runs perfectly!

Best regards,
Rui
